### PR TITLE
OpenZFS 2.0.2. autoconf-2.70 compat. zfs-dkms adds config/compile.

### PR DESCRIPTION
**Pull request by jonathonf**
Update for 2.0.1, though this will need to wait until autoconf>2.7**0** (https://github.com/openzfs/zfs/issues/11413). :frowning_face:

Mainly a bump except for an extra file required for the DKMS module (https://github.com/eli-schwartz/pkgbuilds/compare/master...jonathonf:openzfs-2.0.1?expand=1#diff-1f3ea460ddb6d2527d395cc73357cf0424dce90bc2cb2b261193efb9d9d1e6d3).

### CODE REVIEW

**Comment by eli-schwartz** [comment]
> though this will need to wait until autoconf>2.7 

Autoconf 2.70 was recently released, which is 63 versions newer than 2.7 -- however, it is true this needs 2.70.1 or 2.71 (whichever the autoconf maintainers decide to use, incidentally in part due to a desire to prevent people from calling it "2.7".

Thanks! I'll take a look later this week (hopefully once the autoconf maintenance bugfix is released).

**Comment by jonathonf** [comment]
D'oh. Yes, I meant 2.70... :pensive:

The patch [you pointed out](https://github.com/openzfs/zfs/issues/11413#issuecomment-754384988) in the other issue thread isn't present in 2.70 so ZFS fails to build with the expected error. I locally [patched](https://git.savannah.gnu.org/cgit/autoconf.git/commit/?h=branch-2.70&id=35b1708c3961dce31e4ce43014e71d77aa4b5e31) `autoconf` to check it works (and it does :grin:).

**Comment by jonathonf** [comment]
I got bored of waiting for the Autoconf 2.70+ fix so for Open ZFS 2.0.2 I've included Brian's Autoconf 2.70 patch so `zfs-dkms` will compile without erroring out.

**Comment by jonathonf** [comment]
Oh good grief.

**Comment by eli-schwartz** [comment]
Meanwhile, 2.71 just landed in testing. :p Can you force push a commit that goes straight from 2.0.0 to 2.0.2 and fixes config/compile, and does not include 0002-autoconf-270-compat.patch?

**Comment by jonathonf** [comment]
Sneaky autoconf...

PR updated.

**Pull request merged**
