### PR TITLE
[zfs-dkms] Backport kernel 5.12 compat and update patches

### PR DESCRIPTION
**Pull request by jonathonf**
This backports https://github.com/openzfs/zfs/commit/e2a8296131e94ad785f5564156ed2db1fdb2e080 and https://github.com/openzfs/zfs/commit/ffd6978ef59cfe2773e984bf03de2f0b93b03f5c for kernel 5.12 compatibility.

### CODE REVIEW

**Comment by jonathonf** [comment]
Tested with `linux-zen=5.12.0` and seems to work OK.

**Comment by eli-schwartz** [comment]
Sorry, this slipped my attention. I'll review it when I get home.

Quick question: has this been backported into upstream's staging branch for the next maintenance release? And, can we retrieve the patch from github rather than checking it into the repo? (May not work if it needs to resolve conflicts, but if the patch is backported to the staging branch it will include the conflict resolution in the backported version.)

**Comment by jonathonf** [comment]
It hasn't been backported into the staging branch, the patches needed some minor changes to apply to the 2.0.4 branch so I checked it in here... I wonder whether I should be opening a PR against https://github.com/openzfs/zfs/tree/zfs-2.0.5-staging... :thinking:

If that's a better approach then don't merge this and I'll open a PR upstream instead.

**Comment by eli-schwartz** [comment]
Ideally both! Opening a `[backport]` PR for zfs-2.0.5-staging helps distros to collaborate and makes it easier for upstream to incrementally prepare the next maintenance release.

Independent of that, we should backport this in arch, ahead of the non-existent 2.0.5 final tag.

**Comment by eli-schwartz** [comment]
For my part as I was one of the people who convinced them to open that staging branch, I would like to demonstrate my participation by asking for any backports here, to be opened there as well -- even if I don't wait for them to merge the backport, at least to get the wheels in motion and indicate we've backported it... :)

So yes, it would be great if you always open two PRs, one here and one there.

**Comment by jonathonf** [comment]
OK, let's try https://github.com/openzfs/zfs/pull/12009

**Comment by eli-schwartz** [comment]
Force pushed on top of git master and to PGP-sign the commit. I also took the liberty of re-ordering the patch urls to reduce the difflog changes for `"0001-only-build-the-module-in-dkms.conf.patch")` getting shuffled (that ending parenthesis :p).

Also I dropped the changes to that same patch as they turned out to not be necessary (they only affected "Hunk #1 succeeded at 26 with fuzz 2 (offset 1 line)." and fuzz is fine).

Thanks! Tested fine locally and fixed the build failure.

**Pull request merged**
